"""Removed column add info from users

Revision ID: 15881abe7077
Revises: 389193a7b46c
Create Date: 2024-05-10 21:00:21.726567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15881abe7077'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
